[project]
name = "timecodes-generator"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "eyed3>=0.9.9",
    "nvidia-cuda-runtime-cu12",
    "nvidia-cudnn-cu12>=9.10.2.21",
    "pydub>=0.25.1",
    "whisperx>=3.7.4",
]
